# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Yehan
tagline:          'Blog'
description:      'A CS student'
url:              http://hyde.getpoole.com
baseurl:          /

author:           
  name:           'Mark Otto'
  url:            https://twitter.com/mdo
#Gems
gems: 
  - jekyll-paginate
  - jekyll-gist

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/hyde

