# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Yehan
tagline:          '1+1=10'
description:      'Programming beginner'
url:              http://yehan-xiao.github.io
baseurl:          /


# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed


author:           
  name:           'Yehan Xiao'
  url:            
#Gems
gems: 
  - jekyll-paginate
  - jekyll-gist

paginate:         6

# Custom vars
version:          1.0.0

github:           
  repo:           https://github.com/poole/hyde

