# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Yehan
tagline:          '1+1=10'
description:      'Programming beginner'
url:              http://yehan-xiao.github.io
baseurl:          /

author:           
  name:           'Yehan Xiao'
  url:            
#Gems
gems: 
  - jekyll-paginate
  - jekyll-gist

paginate:         5

# Custom vars
version:          1.0.0

github:           
  repo:           https://github.com/poole/hyde

